[18] [FE] [Feature] - Criar produto e serviço.
RSN-Solucoes/fature-front pull request #14
Opened 2022-12-13 14:05 UTC by hugosique

Descrição:
Foram criados os formulários para cadastro de produtos e serviços no sistema. Na tela de listagem de produtos e serviços foi incluído um modal para navegação aos formulários criados.

Contexto:
Necessidade de cadastro dos produtos e serviços de forma separada (cada um em seu respectivo formulário).

2022-12-13 15:45 UTC, Sczayka requested changes

2022-12-13 15:45 UTC, Sczayka commented on src/app/modules/products-services/products-services-list/products-services-list.component.html
> +    <div class="dialog---header">
Esta com um ifem a mais

2022-12-13 15:45 UTC, Sczayka commented on src/app/modules/products-services/products-services-list/products-services-list.component.scss
> +    .dialog---header {
Esta com um ifem a mais

2022-12-13 15:45 UTC, Sczayka commented on src/app/modules/products-services/products-services-list/products-services-list.component.html
> +          <i class="pi pi-th-large"></i>
Alterara para PNG anexado no card do trello

2022-12-13 15:45 UTC, Sczayka commented on src/app/modules/products-services/products-services-list/products-services-list.component.html
> +          <i class="pi pi-briefcase"></i>
Alterara para PNG anexado no card do trello

2022-12-13 15:45 UTC, Sczayka commented on src/app/modules/products-services/products-services-list/products-services-list.component.ts
> +    this.router.navigate(['painel/produtos-e-servicos/novo-produto']);
Criar um unico formulario que crie tanto produto quanto serviço e manter o padrão de nomenclatura nas rota
"novo"

2022-12-15 16:39 UTC, Sczayka commented on src/app/core/interfaces/invoice.interface.ts
> +// import { I_Billing } from "./billing.interface";
Por que o arquivo inteiro está comentado?

2022-12-15 16:39 UTC, Sczayka commented on src/app/core/interfaces/product.interface.ts
> +  _id?: string;
Renomear _id para id em todas as interfaces

2022-12-15 16:39 UTC, Sczayka commented on src/app/core/interfaces/user.interface.ts
> +export interface I_User {
Renomear interface para I_Client

2022-12-15 16:39 UTC, Sczayka commented on src/app/core/interfaces/user.interface.ts
> +  clientId: string;
remover chave

2022-12-15 18:02 UTC, Sczayka commented on src/app/core/interfaces/user.interface.ts
> +export interface I_Client {
Renomear arquivo para user.interface

2022-12-15 18:05 UTC, hugosique commented on src/app/core/interfaces/user.interface.ts
> +export interface I_Client {
renomeado para 'client.interface'.

2022-12-15 23:06 UTC, Sczayka approved these changes

2022-12-15 23:06 UTC, merged